# Generated by Django 5.2.3 on 2025-06-25 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0006_district_region_remove_fieldlocation_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(choices=[('begins', 'Begins'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20)),
                ('date', models.DateTimeField(verbose_name='YYYY-MM-DD HH:MM')),
                ('bron_created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bron_field', to='field.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bron_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('field', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ComplaintToOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.bron')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_to_owner_sent', to=settings.AUTH_USER_MODEL)),
                ('to_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_to_owner_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.bron')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('from_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_to_user_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_to_user_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='YYYY-MM-DD HH:MM')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='YYYY-MM-DD HH:MM')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='bron.bron')),
            ],
        ),
    ]
