# Generated by Django 5.2.3 on 2025-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainttouser',
            name='bron',
        ),
        migrations.RemoveField(
            model_name='complainttouser',
            name='field',
        ),
        migrations.RemoveField(
            model_name='complainttouser',
            name='from_owner',
        ),
        migrations.RemoveField(
            model_name='complainttouser',
            name='to_user',
        ),
        migrations.AlterField(
            model_name='bron',
            name='situation',
            field=models.CharField(choices=[('begins', 'Begins'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='begins', max_length=20),
        ),
        migrations.DeleteModel(
            name='ComplaintToOwner',
        ),
        migrations.DeleteModel(
            name='ComplaintToUser',
        ),
    ]
