# Generated by Django 5.2.3 on 2025-06-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_remove_fieldlocation_ower_fieldlocation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldlocation',
            name='owner',
        ),
    ]
