# Generated by Django 5.2.3 on 2025-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_remove_fieldlocation_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
